import { Document, Image, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import QRCode from 'qrcode'
import { useEffect, useState } from "react";

const data = [{
    id: 23124124,
    product: 'Soup',
    quantity: 5,
    subtotal: 23424,
}, 
{
    id: 23124125,
    product: 'Soup',
    quantity: 5,
    subtotal: 23424,
},
{
    id: 23124126,
    product: 'Soup',
    quantity: 5,
    subtotal: 23424,
}, 
{
    id: 23124127,
    product: 'Soup',
    quantity: 5,
    subtotal: 23424,
}, 
{
    id: 23124128,
    product: 'Soup',
    quantity: 5,
    subtotal: 23424,
}, 
{
    id: 23124129,
    product: 'Soup',
    quantity: 5,
    subtotal: 23424,
}]

export default function InvoicePdf({order}) {
    const [ orderQrCode, setOrderQrCode ] = useState('');
    useEffect(() => {
        const getOrderQr = async(id) => {
            try {
                const qrCode =  await QRCode.toDataURL(id);
                setOrderQrCode(qrCode);
            } catch(e) {
                console.log(e);
            }
        }

        getOrderQr(order._id);
    }, [])
    return (
        <Document>
            <Page size={{width: 250, height: 'auto'}} style={styled.page}>
                <View style={styled.header} >
                    <Image style={{width: 90, objectFit: 'cover', objectPosition: 'center'}} src='/logo-black.png' />
                    <Text style={{maxWidth: 120, textAlign: 'center'}}>
                        HCMUS Canteen System
                    </Text>
                </View>

                <View style={{margin: '8px 0', display: 'flex', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'}}>
                    <View>
                        <Text>ID: {order._id}</Text>
                        <Text>{order.createdAt}</Text>
                    </View>
                    <View>
                        <Image src={orderQrCode} style={{width: 50, height: 50}} />
                    </View>
                </View>

                <View style={styled.table}>
                    {order.products.map(elem => (
                        <View key={elem.product.name} style={styled.tableRow}>
                            <Text style={{width: '40%'}}>
                                {elem.product.name}
                            </Text>
                            <Text style={{width: '20%'}}>
                                x{elem.quantity}
                            </Text>
                            <Text style={{width: '40%'}}>
                                {elem.product.price * elem.quantity} VND
                            </Text>
                        </View>
                    ))}
                    <View style={{marginTop: '6px', width: '100%', textAlign: 'end', justifyContent: 'flex-end'}}>
                        <Text style={{fontWeight: 'bold'}}>Total: {order.products.reduce((acc, row) => acc += row.product.price * row.quantity, 0)}VND</Text>
                    </View>
                </View>
                <View style={{textAlign: 'center', marginTop: '12px'}}>
                    <Text>***************************</Text>
                    <Text>Thanks for shopping</Text>
                    <Text>This invoice was generated by Canteen Dashboard</Text>
                </View>
            </Page>
        </Document>
    )
}

const styled = StyleSheet.create({
    page: {
        fontSize: '10px',
        width: 200,
        height: 'auto',
        padding: '6px 8px'
    },
    header: {
        flexDirection: 'row',
        display: 'flex',
        justifyContent: 'space-between',
        fontSize: '14px'
    },
    table: {
        width: '80%',
        marginLeft: 'auto',
        marginRight: 'auto',
        display: 'flex',
        flexDirection: 'column'
    },
    tableRow: {
        display: 'flex',
        flexDirection: 'row'
    }
})